question_example = [
    "List suppliers who supply red parts.",
    "List suppliers who supply green parts",
    "List the number of suppliers who supply green parts.",
    "List suppliers who do not supply red parts.",
    "List suppliers who do not supply part P2",
    "List suppliers who supply all parts.",
    "List suppliers who supply all red parts.",
    "List suppliers who supply all red parts or are not located in Paris.",
    "List suppliers who supply all red parts and are not located in Paris.",
    "List suppliers who do not supply all parts",
    "List suppliers who do not supply all red parts",
    "List suppliers who do not supply all blue parts",
    "List the parts that are supplied by London supplier",
    "List parts that are supplied by the supplier named Clark",
    "List parts which are supplied by S1",
    "List parts that are not supplied by Smith",
    "List parts that are not supplied by Jones",
    "List parts that are supplied by all suppliers",
    "List the parts that are not supplied by all suppliers",
    "List the name of suppliers that are located in London",
    "List the suppliers who are located in London",
    "List the number of suppliers that are located in London.",
    "List suppliers whose locations are not in Paris",
    "List suppliers who are not located in Paris",
    "List parts that are stored in Rome.",
    "List the number of parts that are stored in London.",
    "List parts that are stored in Rome and are blue.",
    "List part numbers that are stored in Rome.",
    "List the number of parts whose stored in Paris.",
    "List the number of parts whose color are blue and are stored in Paris.",
    "list suppliers who supply part P2",
    "list the city of suppliers who supply part P5",
    "list the status of suppliers who supply part P5"
]